game data structure changes + bug fixes and minor feature work
OctoPuzzles/octopuzzles pull request #160
Opened 2023-04-24 11:37 UTC by starwarigami

This provides the foundation for other features to be pulled in at a later date, and improves memory usage during gameplay

- Closes #129
- Closes #123
- Closes #121
- Closes #120

2023-04-26 18:54 UTC, SorenHolstHansen requested changes
Overall this is really great!

I have a few comments here and there, and the preview is failing, so will wait for that to go through so I can look at it live.

But other than that, this is really great!

2023-04-26 18:54 UTC, SorenHolstHansen commented on apps/website/src/routes/sudoku/editor/+page.svelte
> +              return !cell.digits && finalStep.cellValues[i][j].digits;
```suggestion
              return cell.digits !== "" && finalStep.cellValues[i][j].digits;
```
Or what is meant here

2023-04-26 18:54 UTC, SorenHolstHansen commented on apps/website/src/routes/sudoku/editor/+page.svelte
> +    </details>
Is this the same as in the other page? If so, can we pull it out into its own component?

2023-04-26 18:54 UTC, SorenHolstHansen commented on apps/website/src/routes/sudoku/editor/+page.svelte
> +    </details>
The same with this

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/icons/src/lib/icons/CtC.svelte
> -<svg xmlns="http://www.w3.org/2000/svg" fill="#000000" viewBox="0 0 256 256">
Just for my interest: Have they changed icon?

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/icons/src/lib/icons/FPuzzles.svelte
> +  </defs>
Is this needed? fonts are very heavy to import, so would hope we could remove this.

If not, take a look at [this](https://developers.google.com/fonts/docs/getting_started#optimizing_your_font_requests) which can optimize it

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CenterMarks.svelte
> +        {#if centermarks !== undefined && givens[row][column] === '' && cell.digits === undefined}
Prefer checking equality and inequality with null, as both undefined and null is == null, but only undefined is === undefined
```suggestion
        {#if centermarks != null && givens[row][column] === '' && cell.digits == null}
```

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Colors.svelte
> +      {#if gameColors !== undefined}
```suggestion
      {#if gameColors != null}
```

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte
> +        {#if cornermarks !== undefined && givens[row][column] === '' && cell.digits === undefined}
```suggestion
        {#if cornermarks != null && givens[row][column] === '' && cell.digits == null}
```

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte
> +            {#if i < 8}
What is this for? Are we ignoring cornermarks if there are too many?

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte
> +              {@const k = getPosition(n, i)}
It would be nice with some more descriptive names than n, i and k

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte
> +  }
I have no clue what this does ;) Can you put some comments in?

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Numbers.svelte
> +      {#if digits !== undefined}
```suggestion
      {#if digits != null}
```

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-editor/src/lib/sudokuStore/index.ts
> +    });
Niiice!

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-game/src/lib/Game/Controller/components/CenterMarks.svelte
> +          delete newCellValues[p.row][p.column].centermarks;
Is there another solution than deleting here, I don't like the potential side effects (as explained in [this](https://eslint.org/docs/latest/rules/no-delete-var))

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-game/src/lib/Game/Controller/components/CornerMarks.svelte
> +          delete newCellValues[p.row][p.column].cornermarks;
Same here

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-game/src/lib/Game/Controller/components/GameColors.svelte
> +          delete newCellValues[p.row][p.column].colors;
And here

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-game/src/lib/Game/Controller/components/GameColors.svelte
> +      const clearAllGameCells = positions.every((p) => !currentCellValues[p.row][p.column].colors);
```suggestion
      const clearAllGameCells = positions.every((p) => currentCellValues[p.row][p.column].colors !== "");
```

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-game/src/lib/Game/Controller/components/GameColors.svelte
> +                .map((n) => Colors[n]);
Something like this would be better i think. Not sure if it should be this, or the other way round, i.e. `Colors.indexOf(b) - Colors.indexOf(a)`
```suggestion
                .sort((a, b) => Colors.indexOf(a) - Colors.indexOf(b))
```

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-game/src/lib/Game/Controller/components/Numbers.svelte
> +              delete newCellValues[p.row][p.column].cornermarks;
And here

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-game/src/lib/sudokuStore/scanner.ts
> +          })
Move this out into a constant outside the if-statement and give it a descriptive name

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-game/src/lib/sudokuStore/scanner.ts
> +				}*/
Delete this?

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/sudoku-game/src/lib/sudokuStore/scanner.ts
>      toggleTuples,
Not a comment on this line, but is there anyway this store can be simplified? I would have no clue how to even begin if I had to fix anything here ;)

Perhaps pull something out into util functions, or something?

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/utils/src/utils/getValuesFromRange.ts
> +export function getValuesFromRange(range: string): string[] {
Add a comment to this function to document what its purpose is

2023-04-26 18:54 UTC, SorenHolstHansen commented on packages/utils/src/utils/getValuesFromRange.ts
> +        }
What does this do? And is it possible to do it without char-codes? Feels like magic

2023-04-27 08:23 UTC, starwarigami commented on apps/website/prisma/seed.ts
> -      difficulty: 4,
I updated the puzzle constraints to use the prefabs so that the constraint validation in the upcoming PR can be tested

2023-04-27 08:31 UTC, starwarigami commented on apps/website/src/features/fpuzzles/exportAsFPuzzlesJson.ts
> +    disjointgroups: flags.includes('DisjointSets') ? true : undefined,
Merge issue

2023-04-27 08:34 UTC, starwarigami commented on apps/website/src/routes/sudoku/editor/+page.svelte
> +          return digits.length ? { digits: digits.map((d) => d as Digit) } : {};
Done - wasn't aware this was an option

2023-04-27 08:49 UTC, starwarigami commented on apps/website/src/features/fpuzzles/exportAsFPuzzlesJson.ts
> +    disjointgroups: flags.includes('DisjointSets') ? true : undefined,
This was not an intentional change, rather a merge issue where we both fixed the indexOf('<FLAGNAME>') == -1 inefficiency independently and I merged my changes on top of yours for ease of solving the file merge

2023-04-27 08:50 UTC, starwarigami commented on apps/website/src/routes/sudoku/[id]/+page.svelte
> +  </details>
I'll send you a screenshot

2023-04-27 08:52 UTC, starwarigami commented on packages/utils/src/utils/getValuesFromRange.ts
> +        }
Comment added to function

//Converts a string of the form "1-9" into an array of all chars in the range, e.g. [1,2,3,4,5,6,7,8,9]
//Can handle multiple different ranges in a single, separated by ";", "," or " "
//e.g. "0-3; A,B,C X-Z" -> [0,1,2,3,A,B,C,X,Y,Z]

The function is building a range of characters, so incrementing the char code seemed like the obvious way to approach it

2023-04-27 08:57 UTC, starwarigami commented on packages/icons/src/lib/icons/CtC.svelte
> -<svg xmlns="http://www.w3.org/2000/svg" fill="#000000" viewBox="0 0 256 256">
No, but we were not using the CtC icon up to this point. I had put a placeholder in that was the closest phospor icon that resembled theirs, but I finally tracked down an image I could convert into a usable svg of the genuine article

2023-04-27 08:58 UTC, starwarigami commented on packages/icons/src/lib/icons/FPuzzles.svelte
> +  </defs>
Not needed in the slightest. I just wanted to add an F into the puzzle piece for clarity, since f-puzzles doesn't have an icon of its own

2023-04-27 09:03 UTC, starwarigami commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CenterMarks.svelte
> +        {#if centermarks !== undefined && givens[row][column] === '' && cell.digits === undefined}
but neither cell.centremarks or cell.digits can ever be null, so why would I need to check for it?

export const CellDataValidator = z.object({
  digits: z.array(DigitValidator).optional(),
  centermarks: z.array(DigitValidator).optional(),
  cornermarks: z.array(DigitValidator).optional(),
  colors: z.array(ColorValidator).optional()
});

They are defined as optional, not nullish - is that a problem?

2023-04-27 09:05 UTC, starwarigami commented on packages/sudoku-game/src/lib/Game/Controller/components/GameColors.svelte
> +                .map((n) => Colors[n]);
good idea

2023-04-27 09:12 UTC, starwarigami commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte
> +  }
Will do.

FYI, It spaces the corner marks out for clarity so they don't interfere with the centremarks. For up to 3 cornermarks it uses the top row, for up to 6 it uses the top and bottom rows, and for 7 or 8 it uses the left and right of the middle row. If you're using all 9 digits as cornermarks then you're solving the puzzle wrong!

2023-04-27 09:19 UTC, starwarigami commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte
> +  }
Done

2023-04-27 09:21 UTC, starwarigami commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Colors.svelte
> +      {#if gameColors !== undefined}
The fields of CellData object can never be null so seems unnecessary to check for it?

2023-04-27 09:21 UTC, starwarigami commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte
> +        {#if cornermarks !== undefined && givens[row][column] === '' && cell.digits === undefined}
The fields of CellData object can never be null so seems unnecessary to check for it?

2023-04-27 09:21 UTC, starwarigami commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Numbers.svelte
> +      {#if digits !== undefined}
The fields of CellData object can never be null so seems unnecessary to check for it?

2023-04-27 09:22 UTC, starwarigami commented on packages/sudoku-game/src/lib/sudokuStore/scanner.ts
>      toggleTuples,
MIght be safer to do this in another branch?

2023-04-27 09:33 UTC, starwarigami commented on packages/sudoku-game/src/lib/sudokuStore/scanner.ts
> +				}*/
I fell like it's there to remind me of something? I don't remember what...

2023-04-27 18:12 UTC, SorenHolstHansen commented on packages/icons/src/lib/icons/FPuzzles.svelte
> +  </defs>
Try it without the font then, don't want a whole font being loaded in

2023-04-27 18:14 UTC, SorenHolstHansen commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CenterMarks.svelte
> +        {#if centermarks !== undefined && givens[row][column] === '' && cell.digits === undefined}
No, not a problem. Checking against null instead of undefined is just preferred as you then catch all "nullishness" instead of just undefinedness.

2023-04-27 18:16 UTC, SorenHolstHansen commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/Colors.svelte
> +      {#if gameColors !== undefined}
See above comment

2023-04-27 18:18 UTC, SorenHolstHansen commented on packages/sudoku-display/src/lib/sudoku-display/sudoku-clues/CornerMarks.svelte
> +            {#if i < 8}
Yeah alright, but a bit weird to just not show cornermarks if the user has added them, but I guess it works

2023-04-27 18:25 UTC, SorenHolstHansen commented on packages/sudoku-game/src/lib/sudokuStore/scanner.ts
>      toggleTuples,
Yeah, agree

2023-04-27 18:27 UTC, SorenHolstHansen commented on packages/utils/src/utils/getValuesFromRange.ts
> +        }
Aaarh, right, the comments made it much clearer, thanks

2023-04-28 08:44 UTC, starwarigami commented on packages/sudoku-game/src/lib/sudokuStore/scanner.ts
> +				}*/
I can deal with this in the future branch where I refactor the scanner code. I think it's something important that I need to get working, but I'll need to delve into it properly to figure out what I was trying to do and why I commented it out

2023-04-28 09:15 UTC, starwarigami commented on packages/icons/src/lib/icons/FPuzzles.svelte
> +  </defs>
Font removed - I draw the F with a polygon now

2023-04-28 17:35 UTC, SorenHolstHansen commented on packages/sudoku-game/src/lib/sudokuStore/scanner.ts
> +				}*/
Cool, no problem then

2023-04-28 17:40 UTC, SorenHolstHansen approved these changes

2023-04-28 17:40 UTC, merged