Walkthroughs
OctoPuzzles/octopuzzles pull request #70
Opened 2022-12-14 10:21 UTC by starwarigami

Auto scanner functionality

2022-12-14 22:42 UTC, SorenHolstHansen requested changes

2022-12-14 22:42 UTC, SorenHolstHansen commented on .vscode/launch.json
> +{
Delete this file and put it in .gitignore

2022-12-14 22:42 UTC, SorenHolstHansen commented on src/icons/AutoScan.svelte
> +<svg
Use phosphor icons

2022-12-14 22:42 UTC, SorenHolstHansen commented on src/icons/Pause.svelte
> +<svg
use Phosphor icons

2022-12-14 22:42 UTC, SorenHolstHansen commented on src/icons/Play.svelte
> +<svg
use Phosphor icons

2022-12-14 22:42 UTC, SorenHolstHansen commented on src/icons/Scanner.svelte
> +<svg
use Phosphor icons if there is an alternative

2022-12-14 22:42 UTC, SorenHolstHansen commented on src/icons/Step.svelte
> +<svg
use Phosphor icons

2022-12-14 22:42 UTC, SorenHolstHansen commented on src/server/trpc/users.ts
> +      }
```suggestion
      if (ctx.token != null) {
        const settingsRaw = await ctx.prisma.userSettings.findUnique({ where: { userId: ctx.token.id } });
        if (settingsRaw != null) {
          const settings = UserSettingsValidator.parse(settingsRaw);
          if (settings != null) {
            return settings;
          }
        }     
      }
```

2022-12-14 22:42 UTC, SorenHolstHansen commented on src/server/trpc/users.ts
> +      }
```suggestion
      if (ctx.token == null) {
        throw new TRPCError({ message: 'You are not logged in', code: 'UNAUTHORIZED' });
      }
      try {
        await ctx.prisma.userSettings.create({
          data: { userId: ctx.token.id, ...input }
        });
      } catch (e) {
        
      await ctx.prisma.userSettings.update({
        where: { userId: ctx.token.id },
        data: { userId: ctx.token.id, ...input}
      });
      }
```

2022-12-14 22:42 UTC, SorenHolstHansen commented on src/stores/sudokuStore/scanner.ts
> +export const scanner = createScannerStore();
This file is very long and the functions are difficult to figure out. Is it possible to split into more files, or to split the functions up into smaller ones

2022-12-15 05:53 UTC, starwarigami commented on src/icons/AutoScan.svelte
> +<svg
Done

2022-12-15 05:53 UTC, starwarigami commented on src/icons/Pause.svelte
> +<svg
Done

2022-12-15 05:53 UTC, starwarigami commented on src/icons/Play.svelte
> +<svg
Done

2022-12-15 05:53 UTC, starwarigami commented on src/icons/Scanner.svelte
> +<svg
Done

2022-12-15 05:54 UTC, starwarigami commented on src/icons/Step.svelte
> +<svg
There is no composite Play/Pause icon, so the custom icon is necessary here

2022-12-15 07:33 UTC, starwarigami commented on .vscode/launch.json
> +{
Done

2022-12-15 07:33 UTC, starwarigami commented on src/server/trpc/users.ts
> +      }
Taken suggested code

2022-12-15 18:38 UTC, SorenHolstHansen commented
There are some merge conflicts, I will rereview after those are resolved :)

2022-12-19 18:43 UTC, SorenHolstHansen submitted a review, later dismissed
Looks really good. There is just the one thing which I wrote below, otherwise you are good to merge after you have fixed merge conflicts

2022-12-19 18:43 UTC, SorenHolstHansen commented on src/icons/Scanner.svelte
> +<Crosshair size={64} />
I think you should inline this component wherever you are using it instead of making a wrapper component

2022-12-19 21:56 UTC, starwarigami commented
The wrapper is so that I can override the default size of the phosphor
icon. The Controller requires all button icons to be the NumbersIcon type,
which doesn't have a size property

On Tue, 20 Dec 2022, 7:43 am SorenHolstHansen, ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Looks really good. There is just the one thing which I wrote below,
> otherwise you are good to merge
> ------------------------------
>
> In src/icons/Scanner.svelte
> <https://github.com/OctoPuzzles/octopuzzles/pull/70#discussion_r1052519944>
> :
>
> > -  /><circle
> -    cx="128"
> -    cy="128"
> -    r="32"
> -    fill="none"
> -    stroke="#000000"
> -    stroke-linecap="round"
> -    stroke-linejoin="round"
> -    stroke-width="16"
> -  /></svg
> ->
> +<script>
> +  import Crosshair from 'phosphor-svelte/lib/Crosshair/Crosshair.svelte';
> +</script>
> +
> +<Crosshair size={64} />
>
> I think you should inline this component wherever you are using it instead
> of making a wrapper component
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OctoPuzzles/octopuzzles/pull/70#pullrequestreview-1223359394>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJXMHM4MI3U2BCHICKPDJXTWOCUEVANCNFSM6AAAAAAS6JFVAU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-22 21:08 UTC, SorenHolstHansen approved these changes

2022-12-22 21:08 UTC, merged