Mh updates 12 22
OctoPuzzles/octopuzzles pull request #95
Opened 2023-01-07 09:55 UTC by starwarigami

2023-01-07 23:28 UTC, SorenHolstHansen requested changes
Nice stuff here. I have a few comments, and you should fix the merge conflicts as well

2023-01-07 23:28 UTC, SorenHolstHansen commented on src/routes/sudoku/[id]/+page.ts
> +      ? (decompressFromBase64(dataParam.replace(/ /g, '+')) as SolutionStep)
Can you leave a comment as to why it is needed to replace with a plus sign here?

2023-01-07 23:28 UTC, SorenHolstHansen commented on src/features/walkthroughs/WalkthroughEditor.svelte
> +  });
This looks nice, however I think you should take a look at the [lifecycle/beforeUpdate and afterUpdate tutorial](https://svelte.dev/tutorial/update) to see if that solution is better here. It would be nice t get rid of the querySelector here

2023-01-07 23:28 UTC, SorenHolstHansen commented on src/utils/compressor.ts
> +export function compressToBase64(input: any): string {
Why remove the type here? and can you explain a bit more all the changes in this file?

2023-01-09 08:46 UTC, starwarigami commented on src/routes/sudoku/[id]/+page.ts
> +      ? (decompressFromBase64(dataParam.replace(/ /g, '+')) as SolutionStep)
No idea why it's needed! But that's what it does when it takes the uncompressed the f-puzzles data from the url, and if you don't do it you get errors.

I copied it from here: src\routes\sudoku\fpuzzle\+page.svelte

2023-01-09 08:53 UTC, starwarigami commented on src/utils/compressor.ts
> +export function compressToBase64(input: any): string {
There's nothing specific about the compression function that depends on the FPuzzleJson data structure. I use the same function to generate the url when launching the solver from the standalone walkthrough viewer. I could have changed the function to expect FpuzzlesJson | SolutionStep, but it will happily compress any input, so I though I'd leave it generic in case we need it for anythign else in the future.
I've have just replaced any with unknown though, to get rid of the warnings

2023-01-09 08:56 UTC, starwarigami commented on src/utils/compressor.ts
> +export function compressToBase64(input: any): string {
All changed in the file was to separate the generic compression algorithm from the FPuzzles data structure, and move the latter to its own file. I don't think anything has actually changed from a logical perspectiuve

2023-01-09 10:03 UTC, SorenHolstHansen commented on src/utils/compressor.ts
> +export function compressToBase64(input: any): string {
Arrrh, of course, nice!

2023-01-10 09:41 UTC, starwarigami commented on src/features/walkthroughs/WalkthroughEditor.svelte
> +  });
I've looked at that tutorial, but I don't see a way to adapt it in this situation. I could bind to the div, but can't work out how I would calculate the scroll height based on the step index

2023-01-10 09:43 UTC, starwarigami commented on src/features/walkthroughs/WalkthroughEditor.svelte
> +  });
I've done another google search, and keep coming back to the querySelector solution. I'd be happy to change it if you have a better way, but I can't see it myself, sorry

2023-01-10 18:21 UTC, SorenHolstHansen commented on src/features/walkthroughs/WalkthroughEditor.svelte
> +  });
No problem, just a thought

2023-01-10 18:21 UTC, SorenHolstHansen commented on src/routes/sudoku/[id]/+page.ts
> +      ? (decompressFromBase64(dataParam.replace(/ /g, '+')) as SolutionStep)
Cool

2023-01-10 19:32 UTC, SorenHolstHansen requested changes
A few more comments, otherwise looks very nice!

2023-01-10 19:32 UTC, SorenHolstHansen commented on src/features/compressor.ts
> -// @ts-nocheck
I don't know why I added this in the first place, but you can remove it (I tried locally, and seems to not throw linting errors). This would also remove the source of the CI errors

2023-01-10 19:32 UTC, SorenHolstHansen commented on src/features/fpuzzles/model.ts
> +// @ts-nocheck
You can remove this line, I don't know why I added it in the first place, and I think you can remove it without errors.

2023-01-10 19:32 UTC, SorenHolstHansen commented on src/features/fpuzzles/model.ts
> +export type HexColor = `#${string}`;
Not a comment to this line, but to the file. Can you call this `types.ts` to align with naming other places?

2023-01-10 19:32 UTC, SorenHolstHansen commented on src/lib/prisma.ts
> +					let dimensions: Dimensions = { rows: sudoku.rows, columns: sudoku.columns };
Thanks!

2023-01-10 19:32 UTC, SorenHolstHansen commented on src/routes/sudoku/[id]/+page.ts
> +			: null
```suggestion
		gameData: dataParam ?? (decompressFromBase64(dataParam.replace(/ /g, '+')) as SolutionStep)
```

2023-01-10 19:32 UTC, SorenHolstHansen commented on src/routes/sudoku/editor/+page.svelte
> +				) {
Can you explain this if statement, not sure I follow

2023-01-10 19:33 UTC, SorenHolstHansen commented on src/features/compressor.ts
>  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
You can remove this line

2023-01-11 06:38 UTC, starwarigami commented on src/routes/sudoku/[id]/+page.ts
> +			: null
correct me if I'm wrong, but wouldn't that return the uncompressed dataParam string if it's provided, or throw a null reference exception if it's not?

2023-01-11 07:14 UTC, SorenHolstHansen commented on src/routes/sudoku/[id]/+page.ts
> +			: null
Oh yeah, sorry ;) But can we return undefined instead of null? In general we should use undefined instead of null if we can to unify how to handle it

2023-01-11 09:04 UTC, starwarigami commented on src/routes/sudoku/[id]/+page.ts
> +			: null
shouldn't be a problem

2023-01-11 09:20 UTC, starwarigami commented on src/routes/sudoku/editor/+page.svelte
> +				) {
The code is checking to see if the final step of the walkthrough has more values inputted than the current state of the game. Explicitly, is there a cell which has no value in the current game state that has a value in the final step of the walkthrough. This prevents solutions from being overwritten if you revert to an earlier step.

2023-01-12 20:27 UTC, SorenHolstHansen commented on src/routes/sudoku/editor/+page.svelte
> +				) {
Arrrh, neat

2023-01-12 20:27 UTC, SorenHolstHansen approved these changes

2023-01-12 20:35 UTC, merged